/*
 * 网站可编辑内容集中存放在这里。
 * 后续替换文字、作品、烘焙秘方和联系方式时，优先修改这个文件。
 */
window.siteData = {
  basic: {
    ownerName: "王珺怡",
    siteName: "ZeroBaker",
  },

  // 首页可编辑文字与导航入口集中放在这里，后续调整文案时无需修改 HTML。
  home: {
    eyebrow: "WELCOME TO MY ONLINE-ONLY BAKERY",
    title: "欢迎你！我是王珺怡",
    intro:
      "这是我的个人网站，也是一家只在网上营业的烘焙坊。这里收集我做过的事、喜欢的东西，以及人生路上偶尔停下来时留下的注脚。戳戳小蛋糕，可以继续逛逛。",
    layover: "A little layover between life, work and everything I love.",
    navigation: [
      { label: "自我介绍", english: "ABOUT THE BAKER", target: "about" },
      { label: "作品展示", english: "FRESHLY BAKED", target: "projects" },
      { label: "烘焙秘方", english: "SECRET RECIPES", target: "recipes" },
      { label: "联系方式", english: "FIND ME", target: "contact" },
    ],
    cakes: [
      {
        label: "自我介绍",
        english: "ABOUT THE BAKER",
        target: "about",
        image: "assets/images/home/home-cake-about.png",
      },
      {
        label: "作品展示",
        english: "FRESHLY BAKED",
        target: "projects",
        image: "assets/images/home/home-cake-projects.png",
      },
      {
        label: "烘焙秘方",
        english: "SECRET RECIPES",
        target: "recipes",
        image: "assets/images/home/home-cake-recipes.png",
      },
      {
        label: "联系方式",
        english: "FIND ME",
        target: "contact",
        image: "assets/images/home/home-cake-contact.png",
      },
    ],
  },

  // 自我介绍的标题、引导语、图片和三份 Recipe 文案都在这里维护。
  about: {
    title: "自我介绍",
    englishTitle: "ABOUT THE BAKER",
    intro:
      "我很难用一个标签概括自己。比起罗列经历，我更愿意从三份配方说起：我如何观察生活、如何投入行动，以及如何把喜欢的事慢慢做成作品。",
    image: {
      src: "assets/images/about/about-main-collage.webp",
      alt: "王珺怡的个人拼贴照片",
    },
    recipes: [
      {
        number: "Recipe 01",
        title: "学习与观察",
        englishTitle: "LEARNING & OBSERVING",
        text: "我本科就读于中国人民大学农业与农村发展学院农林经济管理专业，现在也继续在这里攻读食品经济管理硕士。在人大学习的经历，让我习惯从数据、制度与人的选择之间理解问题；调研与科研训练，以及那段特别的高丽大学交换经历，则让我不断走近真实生活，观察不同的人如何工作、消费、生活，又如何作出自己的决定。",
        theme: "sage",
        icon: "observe",
      },
      {
        number: "Recipe 02",
        title: "工作与行动",
        englishTitle: "WORKING & MAKING THINGS HAPPEN",
        text: "本科毕业后，我在中国人民大学综合保障部全职工作了两年，而后保研攻读硕士学位。这段工作中，我做过新媒体运营，也处理过行政、党务事务，并参与了学校许多大型项目的推进。后来在硕士期间，我进入搜狐担任企业文化实习生，继续接触内容策划、短视频与活动传播。不同角色让我逐渐确认：我既能把复杂的事情稳稳推进，也喜欢把一个想法变成更清楚、更有意思的内容。",
        theme: "caramel",
        icon: "whisk",
      },
      {
        number: "Recipe 03",
        title: "兴趣与创造",
        englishTitle: "LOVING & CREATING",
        text: "追星是我学习创造的另一条路径。为了记录喜欢，我开始剪视频、运营账号、组织线下活动，也在社群与跨文化表达中认识更多的人。现在，我又把好奇心伸向AI、基础编程与Vibe Coding；ZeroBaker——你现在正在浏览的这个网页，就是我第一次把这些兴趣完整做成一个作品。",
        theme: "berry",
        icon: "create",
      },
    ],
  },

  // 作品展示的标题、提示语和卡片公共文字集中放在这里维护。
  projectsSection: {
    title: "作品展示",
    englishTitle: "FRESHLY BAKED",
    intro: "这里是一些已经出炉的近期作品。",
    imageHint: "点击图片查看原作",
    unavailableHint: "原作链接待补充",
    decorativeNote: "fresh from the oven",
  },

  // 每个项目的文字、截图、链接和强调色都由这个数组生成。
  projects: [
    {
      platform: "BILIBILI · VIDEO EDIT",
      title: "《防弹少年团solo，但是用〈怪奇物语〉打开》",
      description:
        "这是我运营的明星娱乐内容账号中的一支混剪作品，账号目前有1500+粉丝，累计播放量120万+。我尝试用《怪奇物语》的悬疑氛围重新组织BTS solo素材，完成选题、素材筛选、结构设计与剪辑包装。",
      image: "assets/images/projects/project-bts-stranger-things.png",
      imageAlt: "BTS成员在红色《怪奇物语》风格舞台上的混剪作品截图",
      url: "https://www.bilibili.com/video/BV1J84y1d7Qb",
      theme: "blueberry",
      objectPosition: "center",
    },
    {
      platform: "XIAOHONGSHU · CONTENT OPERATION",
      title: "搜狐员工采访快剪",
      description:
        "2026年4月至7月，我参与“搜狐young”小红书账号的日常运营，负责选题、脚本、拍摄、剪辑与发布。这支采访快剪是其中一个案例，也记录了我把一个职场话题从创意推进到上线的完整过程。",
      image: "assets/images/projects/project-sohu-interview.png",
      imageAlt: "搜狐young采访快剪封面，画面文字为“狐厂青年请回答 pt.2”",
      url: "https://www.xiaohongshu.com/discovery/item/6a583786000000000f014773?source=webshare&xhsshare=pc_web&xsec_token=ABIwIG49khNwna-gvPxLVwq2EA9-6glLEDXy2-N1JaXsg=&xsec_source=pc_share",
      theme: "strawberry",
      objectPosition: "center",
    },
    {
      platform: "WECHAT · EDITORIAL CONTENT",
      title: "搜狐企业文化活动推送",
      description:
        "这是我在搜狐实习期间参与制作的一篇微信公众号图文，负责内容梳理、文案与排版呈现。它代表了我除短视频之外，在长图文表达和活动传播上的实践。",
      image: "assets/images/projects/project-sohu-wechat.png",
      imageAlt: "“2026搜狐成长生活节”微信公众号活动推送封面",
      url: "https://mp.weixin.qq.com/s/sne4kqxSQGIWNExvvbKOTg",
      theme: "caramel",
      objectPosition: "center",
    },
    {
      platform: "WEB PROJECT · CONTENT & OPERATION",
      title: "decodeBTS 歌词注释网站",
      description:
        "decodeBTS是我和朋友共同搭建的BTS歌词注释网站，希望把翻译、词义和情感语境整理成更容易阅读的内容。我负责内容策划与运营，朋友负责视觉设计与代码，目前项目仍在持续完善。",
      image: "assets/images/projects/project-decode-bts.png",
      imageAlt: "decodeBTS歌词注释网站的歌曲解读页面截图",
      url: "https://decodebts.netlify.app",
      theme: "sage",
      objectPosition: "center",
    },
  ],

  recipesSection: {
    title: "烘焙秘方",
    englishTitle: "SECRET RECIPES",
    intro:
      "这里藏着一些喜欢的事、最近的兴趣，以及想被好好保存的生活瞬间。点开纸团，看看我私藏的配方。",
  },

  // 七份生活纸条的内容与可选媒体都在这里维护；空字段不会生成无效链接或控件。
  recipeNotes: [
    {
      id: "recipe-bts",
      number: "01",
      title: "世界的选择是BTS",
      subtitle: "MY ONE & ONLY, BTS",
      type: "追星",
      body: "沾上这个BTS之前，从来没想过自己追星会这么长情……时隔七年过去，说真的经历了蛮多波折，终于在舞台上看到七个人在一起的样子，也听到了特别喜欢的歌的现场。只觉得这一瞬间太幸福了。以后都只为了幸福而流泪好吗！",
      image: "assets/images/recipes/recipe-bts.jpg",
      imageAlt: "BTS演出现场的七人合照",
      imageWidth: 1024,
      imageHeight: 1366,
      accent: "#A89BC7",
      url: "",
      linkLabel: "",
      audio: "",
      audioLabel: "",
      downloadFile: "",
      downloadLabel: "",
      downloadName: "",
    },
    {
      id: "recipe-travel",
      number: "02",
      title: "好喜欢海边",
      subtitle: "WHERE THE SEA HOLDS EVERYTHING",
      type: "旅行",
      body: "每次去海边旅行的时候都好开心啊。这张照片是在江陵的海边拍摄的，天气很好，风景很好，吃得很美味，和朋友能在国外开车旅行也非常惬意。一望无际的蓝天和大海，世界上的所有东西都能被大海拥入怀中吧。",
      image: "assets/images/recipes/recipe-travel.jpg",
      imageAlt: "江陵海边旅行时拍摄的蓝天与大海",
      imageWidth: 1280,
      imageHeight: 1708,
      accent: "#D6C9B8",
      url: "",
      linkLabel: "",
      audio: "",
      audioLabel: "",
      downloadFile: "",
      downloadLabel: "",
      downloadName: "",
    },
    {
      id: "recipe-fandom",
      number: "03",
      title: "热爱从线上到线下",
      subtitle: "FROM ONLINE LOVE TO OFFLINE ADVENTURES",
      type: "追星",
      body: "因为追星，也做到了许多自己从来没有想过的事：比如一个人勇闯国外爽玩，和不同国家的朋友用蹩脚的英、韩、中三语混合交流，也举办了好多次规模不等的线下活动……就这样，从简单的喜欢里解锁了很多新成就呢～",
      image: "assets/images/recipes/recipe-fandom.jpg",
      imageAlt: "追星线下活动的现场记录",
      imageWidth: 1279,
      imageHeight: 1706,
      accent: "#C98773",
      url: "https://www.bilibili.com/video/BV1iQ4y177uL",
      linkLabel: "看看我策划的自制综艺",
      audio: "",
      audioLabel: "",
      downloadFile: "",
      downloadLabel: "",
      downloadName: "",
    },
    {
      id: "recipe-currently-watching",
      number: "04",
      title: "最近在看的",
      subtitle: "CURRENTLY WATCHING",
      type: "影视",
      body: "就这样错开热度看番哈哈哈。咒术回战好好好，就这样停止在236话之前吧，我会删除掉这之后的所有记忆，嗯嗯呢……",
      image: "assets/images/recipes/recipe-currently-watching.jpg",
      imageAlt: "最近观看的影视作品画面",
      imageWidth: 450,
      imageHeight: 600,
      accent: "#7F8DA3",
      url: "",
      linkLabel: "",
      audio: "",
      audioLabel: "",
      downloadFile: "",
      downloadLabel: "",
      downloadName: "",
    },
    {
      id: "recipe-song",
      number: "05",
      title: "最近在听的",
      subtitle: "ON REPEAT LATELY",
      type: "音乐",
      body: "玩游戏的时候听到的，近来尤为喜欢这种有“画面感”的歌。这首有一种微醺、迷幻的氛围。好吧，主要是听的时候总能想起玩游戏的画面kkk，也很推荐这个歌手GEMINI。",
      image: "assets/images/recipes/recipe-song.webp",
      imageAlt: "最近反复播放的GEMINI歌曲封面",
      imageWidth: 1600,
      imageHeight: 1600,
      accent: "#6F8FAF",
      url: "https://youtu.be/6lJfP4guXD8",
      linkLabel: "去听完整歌曲",
      audio: "assets/audio/recipe-gemini-clip.mp3",
      audioLabel: "试听这段音乐",
      downloadFile: "",
      downloadLabel: "",
      downloadName: "",
    },
    {
      id: "recipe-vibe-coding",
      number: "06",
      title: "最近感兴趣的事",
      subtitle: "MY LATEST RABBIT HOLE",
      type: "Vibe Coding",
      body: "超快速给自己搓了一个Codex桌宠，是我们宇宙大明星BT21的TATA宝贝哈哈哈。打包好上传到了网页上，有Codex的朋友可以自取～",
      image: "assets/images/recipes/recipe-vibe-coding.webp",
      imageAlt: "TATA Codex桌宠的像素动画预览",
      imageWidth: 1600,
      imageHeight: 1040,
      accent: "#B8665C",
      url: "",
      linkLabel: "",
      audio: "",
      audioLabel: "",
      downloadFile: "assets/downloads/tata-codex-pet-pack.zip",
      downloadLabel: "下载TATA桌宠",
      downloadName: "tata-codex-pet-pack.zip",
    },
    {
      id: "recipe-daily-moment",
      number: "07",
      title: "一个生活的瞬间",
      subtitle: "A MOMENT I’LL ALWAYS REMEMBER",
      type: "日常",
      body: "在高丽大学交换期间参加了高延战，感受到了和国内完全不同的氛围，所以印象特别深刻。在国内，体感上大家对体育的关注没有那么高，更何况是两所学校之间的比赛；但那里的学生都十分沉浸地享受竞技与应援。感觉到很久很久以后，我还是会记得自己在体育场唱着《红霞》应援的样子……",
      image: "assets/images/recipes/recipe-daily-moment.webp",
      imageAlt: "高丽大学高延战体育场应援现场",
      imageWidth: 1200,
      imageHeight: 1600,
      accent: "#A46068",
      url: "https://www.xiaohongshu.com/discovery/item/68cfa054000000000b012875?source=webshare&xhsshare=pc_web&xsec_token=ABbVAAojdEFKPAFFUzYIH_LC5DtS8_LX7OcZHU_OoKkYA=&xsec_source=pc_share",
      linkLabel: "看看当时的记录",
      audio: "",
      audioLabel: "",
      downloadFile: "",
      downloadLabel: "",
      downloadName: "",
    },
  ],

  // 联系方式的标题、文案、图片、四个入口与页脚文字都在这里维护。
  contact: {
    title: "联系方式",
    englishTitle: "FIND ME",
    introChinese:
      "欢迎来找我。也许我们可以交换最近的喜欢，或者一起做点有意思的事。",
    introEnglish:
      "Let’s share something we love — or make something new together.",
    image: {
      src: "assets/images/contact/contact-dessert-photo.jpg",
      alt: "装饰着草莓塔、花束与 Best wish 字样的甜品拼贴照片",
    },
    links: [
      {
        label: "小红书",
        english: "XIAOHONGSHU",
        url: "https://xhslink.com/m/2Azd0lCD9H8",
        type: "external",
      },
      {
        label: "哔哩哔哩",
        english: "BILIBILI",
        url: "https://b23.tv/Kq9ttAr",
        type: "external",
      },
      {
        label: "抖音",
        english: "DOUYIN",
        url: "https://v.douyin.com/q73g2FXvflE",
        type: "external",
      },
      {
        label: "邮箱",
        english: "EMAIL",
        display: "bhnmj@qq.com",
        url: "mailto:bhnmj@qq.com",
        type: "email",
      },
    ],
    closingLine: "Maybe we could be slow dancing",
  },

  footer: {
    siteName: "ZeroBaker",
    message: "Made with curiosity, AI and a little courage.",
  },
};
